---
apiVersion: v1
kind: Template
metadata:
  name: edge-api
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: psk-playbook-dispatcher
  stringData:
    key: ${PSK_DISPATCHER}
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: edge-api
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: True
          apiPath: edge
          whitelistPaths:
            - /api/edge/v1/openapi.json
            - /api/edge/v1/storage/update-repos*
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        initContainers:
        - name: run-migrations
          command:
          - bash
          - -c
          - edge-api-migrate
          inheritEnv: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        - name: AUTH
          value: ${ENABLE_RH_IDENTITY_PROCESSING}
        - name: EDGETARBALLSBUCKET
          value: ${EDGE_TARBALLS_BUCKET}
        - name: OPENAPIFILEPATH
          value: ${OPEN_API_FILEPATH}
        - name: IMAGEBUILDERURL
          value: ${IMAGEBUILDER_URL}
        - name: INVENTORYURL
          value: ${INVENTORYURL}
        - name: PLAYBOOKDISPATCHERURL
          value: ${PLAYBOOKDISPATCHERURL}
        - name: FDO_HOST_URL
          value: ${FDO_HOST_URL}
        - name: FDO_API_VERSION
          value: ${FDO_API_VERSION}
        - name: PLAYBOOKDISPATCHERPSK
          valueFrom:
            secretKeyRef:
              key: key
              name: psk-playbook-dispatcher
        - name: EDGEAPIBASEURL
          value: ${EDGEAPIBASEURL}
        - name: UPLOADWORKERS
          value: ${UPLOADWORKERS}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: UNLEASH_URL
          value: ${UNLEASH_URL}
        - name: UNLEASH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ${UNLEASH_SECRET_NAME}
              key: CLIENT_ACCESS_TOKEN
        - name: TENANT_TRANSLATOR_HOST
          value: ${TENANT_TRANSLATOR_HOST}
        - name: TENANT_TRANSLATOR_PORT
          value: ${TENANT_TRANSLATOR_PORT}
        resources:
          limits:
            cpu: ${{CPU_LIMIT}}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 500m
            memory: 512Mi
    - name: images-build
      minReplicas: 0
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
        - /usr/bin/edge-api-images-build
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        - name: AUTH
          value: ${ENABLE_RH_IDENTITY_PROCESSING}
        - name: EDGETARBALLSBUCKET
          value: ${EDGE_TARBALLS_BUCKET}
        - name: OPENAPIFILEPATH
          value: ${OPEN_API_FILEPATH}
        - name: IMAGEBUILDERURL
          value: ${IMAGEBUILDER_URL}
        - name: INVENTORYURL
          value: ${INVENTORYURL}
        - name: PLAYBOOKDISPATCHERURL
          value: ${PLAYBOOKDISPATCHERURL}
        - name: FDO_HOST_URL
          value: ${FDO_HOST_URL}
        - name: FDO_API_VERSION
          value: ${FDO_API_VERSION}
        - name: PLAYBOOKDISPATCHERPSK
          valueFrom:
            secretKeyRef:
              key: key
              name: psk-playbook-dispatcher
        - name: EDGEAPIBASEURL
          value: ${EDGEAPIBASEURL}
        - name: UPLOADWORKERS
          value: ${UPLOADWORKERS}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: UNLEASH_URL
          value: ${UNLEASH_URL}
        - name: UNLEASH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ${UNLEASH_SECRET_NAME}
              key: CLIENT_ACCESS_TOKEN
        - name: TENANT_TRANSLATOR_HOST
          value: ${TENANT_TRANSLATOR_HOST}
        - name: TENANT_TRANSLATOR_PORT
          value: ${TENANT_TRANSLATOR_PORT}
        resources:
          limits:
            cpu: 250m
            memory: 2Gi
          requests:
            cpu: 125m
            memory: 128Mi
    - name: ibvents
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
        - /usr/bin/edge-api-ibvents
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        - name: AUTH
          value: ${ENABLE_RH_IDENTITY_PROCESSING}
        - name: EDGETARBALLSBUCKET
          value: ${EDGE_TARBALLS_BUCKET}
        - name: OPENAPIFILEPATH
          value: ${OPEN_API_FILEPATH}
        - name: IMAGEBUILDERURL
          value: ${IMAGEBUILDER_URL}
        - name: INVENTORYURL
          value: ${INVENTORYURL}
        - name: PLAYBOOKDISPATCHERURL
          value: ${PLAYBOOKDISPATCHERURL}
        - name: FDO_HOST_URL
          value: ${FDO_HOST_URL}
        - name: FDO_API_VERSION
          value: ${FDO_API_VERSION}
        - name: PLAYBOOKDISPATCHERPSK
          valueFrom:
            secretKeyRef:
              key: key
              name: psk-playbook-dispatcher
        - name: EDGEAPIBASEURL
          value: ${EDGEAPIBASEURL}
        - name: UPLOADWORKERS
          value: ${UPLOADWORKERS}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: UNLEASH_URL
          value: ${UNLEASH_URL}
        - name: UNLEASH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ${UNLEASH_SECRET_NAME}
              key: CLIENT_ACCESS_TOKEN
        - name: TENANT_TRANSLATOR_HOST
          value: ${TENANT_TRANSLATOR_HOST}
        - name: TENANT_TRANSLATOR_PORT
          value: ${TENANT_TRANSLATOR_PORT}
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
    - name: isos-build
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
        - /usr/bin/edge-api-isos-build
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        - name: AUTH
          value: ${ENABLE_RH_IDENTITY_PROCESSING}
        - name: EDGETARBALLSBUCKET
          value: ${EDGE_TARBALLS_BUCKET}
        - name: OPENAPIFILEPATH
          value: ${OPEN_API_FILEPATH}
        - name: IMAGEBUILDERURL
          value: ${IMAGEBUILDER_URL}
        - name: INVENTORYURL
          value: ${INVENTORYURL}
        - name: PLAYBOOKDISPATCHERURL
          value: ${PLAYBOOKDISPATCHERURL}
        - name: FDO_HOST_URL
          value: ${FDO_HOST_URL}
        - name: FDO_API_VERSION
          value: ${FDO_API_VERSION}
        - name: PLAYBOOKDISPATCHERPSK
          valueFrom:
            secretKeyRef:
              key: key
              name: psk-playbook-dispatcher
        - name: EDGEAPIBASEURL
          value: ${EDGEAPIBASEURL}
        - name: UPLOADWORKERS
          value: ${UPLOADWORKERS}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: UNLEASH_URL
          value: ${UNLEASH_URL}
        - name: UNLEASH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ${UNLEASH_SECRET_NAME}
              key: CLIENT_ACCESS_TOKEN
        - name: TENANT_TRANSLATOR_HOST
          value: ${TENANT_TRANSLATOR_HOST}
        - name: TENANT_TRANSLATOR_PORT
          value: ${TENANT_TRANSLATOR_PORT}
        resources:
          limits:
            cpu: 250m
            memory: 2Gi
          requests:
            cpu: 125m
            memory: 128Mi
    objectStore:
    - ${EDGE_TARBALLS_BUCKET}
    database:
      name: edge
    testing:
      iqePlugin: edge
    kafkaTopics:
    - replicas: 3
      partitions: 3
      topicName: platform.edge.fleetmgmt.image-build
    - replicas: 3
      partitions: 3
      topicName: platform.edge.fleetmgmt.device-update
    - replicas: 3
      partitions: 3
      topicName: platform.playbook-dispatcher.runs
    - replicas: 3
      partitions: 3
      topicName: platform.inventory.events
    dependencies:
      - unleash-proxy
    optionalDependencies:
      - host-inventory
      - playbook-dispatcher
      - ingress
    featureFlags: true
parameters:
- description: Cpu limit of service
  name: CPU_LIMIT
  required: false
  value: "1"
- description: Memory limit of service
  name: MEMORY_LIMIT
  required: false
  value: 2Gi
- description: Minimum number of edge-api pods to deploy
  name: MIN_REPLICAS
  required: false
  value: "1"
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  required: false
  value: quay.io/cloudservices/edge-api
- description: Determines if Clowder deployment is enabled
  name: CLOWDER_ENABLED
  required: false
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  required: false
- description: Determines if Cloud Watch logging is enabled
  name: ENABLE_CLOUDWATCH_LOGGING
  required: false
  value: "true"
- description: Edge S3 bucket name
  name: EDGE_TARBALLS_BUCKET
  required: false
  value: rh-edge-tarballs
- description: Relative path to JSON version of OpenAPI specification
  name: OPEN_API_FILEPATH
  required: false
  value: /var/tmp/openapi.json
- description: Flag indicating RedHat Identity processing is enabled
  name: ENABLE_RH_IDENTITY_PROCESSING
  required: false
  value: "true"
- description: ImageBuilder service URL
  name: IMAGEBUILDER_URL
  required: false
  value: "http://image-builder:8080"
- description: Host Inventory service URL
  name: INVENTORYURL
  required: false
  value: "http://host-inventory-service:8080/"
- description: Playbook Dispatcher service URL
  name: PLAYBOOKDISPATCHERURL
  required: false
  value: "http://host-playbook-dispatcher:8080/"
- description: Edge-api Base URL
  name: EDGEAPIBASEURL
  required: false
  value: "https://cloud.stage.redhat.com"
- description: Number of workers for uploading to a backing object storage bucket
  name: UPLOADWORKERS
  required: false
  value: "50"
- description: FDO service URL
  name: FDO_HOST_URL
  required: false
  value: "https://fdo.redhat.com"
- description: FDO API version
  name: FDO_API_VERSION
  required: false
  value: "v1"
- description: Log level
  name: LOG_LEVEL
  required: false
  value: "DEBUG"
- description: Unleash API url
  name: UNLEASH_URL
  value: ''
- description: Unleash secret name
  name: UNLEASH_SECRET_NAME
  value: unleash-ephemeral
- description: Host for the EAN to OrgId translator service.
  name: TENANT_TRANSLATOR_HOST
  required: false
  value: 'tenant-translator-host'
- description: Port for the EAN to OrgId translator service.
  name: TENANT_TRANSLATOR_PORT
  required: false
  value: '8892'
